Lab 8
danylyk/py pull request #10
Opened 2019-11-11 20:10 UTC by danylyk

2019-11-12 09:47 UTC, polyakovartem requested changes
the solution is suboptimal, please come up with a better one

2019-11-12 09:47 UTC, polyakovartem commented on P8.py
> +class Directory:
the class name is not informative

2019-11-12 09:47 UTC, polyakovartem commented on P8.py
> +    def get_duplicates (self):
logic is too complex for one function, split it please

2019-11-13 07:22 UTC, polyakovartem requested changes
could you kindly explain why you did not fix other comments?

2019-11-13 09:15 UTC, danylyk commented
What other conments? Suboptimal solution? What does it mean? Other algorithm?

2019-11-13 12:38 UTC, polyakovartem commented
> What other conments? Suboptimal solution? What does it mean? Other algorithm?

well, for instance, the following:
complex logic,
ambiguous class names, etc

please switch to conversation tab and review all of the comments

2019-11-22 10:18 UTC, polyakovartem requested changes
please simplify logic and stop ignoring my comments

2019-11-23 02:13 UTC, danylyk commented
I dont know how to simplify it. It is just algorithm I came up with. Please help me, send the samples may be)

2019-11-26 16:49 UTC, danylyk commented
It works. Try to run it.

2023-04-27 09:33 UTC, closed without merging