Lab 11
danylyk/py pull request #12
Opened 2019-12-10 21:35 UTC by danylyk

2019-12-11 08:16 UTC, polyakovartem requested changes
this will not work correctly

2019-12-11 08:16 UTC, polyakovartem commented on P11.py
> +class RWLock:
it will not work like this, please use threading.Lock for write syncronization

2019-12-11 14:06 UTC, polyakovartem requested changes

2019-12-11 14:06 UTC, polyakovartem commented on P11.py
> +        self.monitor.acquire()
acquire should only happen if the writer thread is present. Otherwise, we have no benefits

2019-12-17 10:49 UTC, danylyk commented
Should I just check if self.write_requests > 0 ?

2019-12-17 14:40 UTC, polyakovartem requested changes
please review this example https://gist.github.com/tylerneylon/a7ff6017b7a1f9a506cf75aa23eacfd6

2019-12-18 07:57 UTC, polyakovartem requested changes

2019-12-18 07:57 UTC, polyakovartem commented on P11.py
> +        self.read_requests = 0
can't you use recursive lock instead of this variable?

2023-04-27 09:33 UTC, closed without merging