Chess-Results.com Notifier
danylyk/py pull request #14
Opened 2019-12-20 21:02 UTC by danylyk

2019-12-20 21:03 UTC, danylyk commented
SMTP Server
![image](https://user-images.githubusercontent.com/22027860/71293051-e437cb00-237c-11ea-9ab8-1b6e4278faea.png)

2019-12-21 18:15 UTC, polyakovartem requested changes
Please make clear subscription API for player and tournament

2019-12-22 14:38 UTC, danylyk commented
You mean my own API?)

2019-12-22 15:12 UTC, polyakovartem commented
Let me rephrase it. I don’t understand how to use your application to subscribe for tournament participant update nor for tournament update

2019-12-24 08:06 UTC, polyakovartem requested changes
in general very good, just few changes needed

2019-12-24 08:06 UTC, polyakovartem commented on data.dv
> +[{"link": "tnr498552.aspx?lan=1", "title": "Bo\u017ei\u0107njak 2019    =   12. Bo\u017ei\u0107ni brzopotezni turnir \u0160K Rijeka ", "data": [[null, null], ["51", "Mihalin\u010di\u0107 Kre\u0161o"]
what is this file for?

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +    def saveing (self):
saveing -> saving

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +class EventNotifier:
please decuple this class from data processing/parsing, the intention of this class should be event notification no more, no less

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +                self.data = json.load(saved_data)
this class should not care about saving data, move this logic out

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +    def append_participant (self, url):
this function is too big, split it into smaller functions with clean names

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +    def get_patricipant_update (self, url):
split this function please

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +    def send_email (self, message):
notification object should not be dependent on emails, what if you need to add more notification transports in the future?

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +            s = smtplib.SMTP('localhost', 1025)
are you sure you need to create a new SMTP connection from every new email?

2019-12-24 08:06 UTC, polyakovartem commented on Chess.py
> +    def tournament_update (self, link, title):
the same comment as for methods from above

2019-12-24 08:06 UTC, polyakovartem commented on Client.py
> +    notifier.append_participant("http://chess-results.com/tnr83447.aspx?lan=1&art=9&snr=23")
append_participant -> subscribe_for_participant_updates

2019-12-24 08:06 UTC, polyakovartem commented on Client.py
> +    notifier.append_tournament("http://chess-results.com/tnr219320.aspx?lan=1")
append_tournament->subscribe_for_tournament_updates

2023-04-27 09:33 UTC, closed without merging