Labs[1-3]
danylyk/py pull request #2
Opened 2019-10-09 18:00 UTC by danylyk

2019-10-10 06:37 UTC, polyakovartem requested changes
each lab must be in a separate pull-request

2019-10-12 19:24 UTC, danylyk commented
Ok, next labs will be in separate pull-request

2019-10-15 08:41 UTC, polyakovartem commented
ok, next lab will get marks then

2019-10-17 19:22 UTC, danylyk commented
If I make this labs in separate pull requests, willl I get marks for them?

2019-10-18 19:46 UTC, closed without merging